### ISSUE TITLE
Scrape content from website

### ISSUE THREAD

**Issue by lintingxue** [nikign/SE-16#31]

**Comment by lintingxue** [comment]
http://stackoverflow.com/questions/1380670/how-do-i-fix-a-merge-conflict-due-to-removal-of-a-file-in-a-branch
http://stackoverflow.com/questions/20909667/git-pull-origin-master-gives-merge-conflict-what-should-i-do
http://stackoverflow.com/questions/25019943/having-trouble-with-git-merge-upstream-master-how-to-handle-a-conflict-conten
http://stackoverflow.com/questions/32454934/git-squashed-merge-with-conflicts-missing-commit-message-content
http://stackoverflow.com/questions/25018602/issue-with-kdiff3-mergetool/25086772
http://stackoverflow.com/questions/22686886/git-subtree-pull-p-whatever-repo-ref-always-merge-conflict
http://stackoverflow.com/questions/4157189/git-pull-while-ignoring-local-changes
http://stackoverflow.com/questions/15986680/openshift-deploying-local-application
http://stackoverflow.com/questions/11696295/rejected-master-master-non-fast-forward
http://stackoverflow.com/questions/linked/161813?page=4&sort=votes
Traceback (most recent call last):
  File "/Users/Linting/Google Drive/CSC510/Project/SE-16/git_helper/GoogleSearch/googleserach.py", line 61, in <module>
    TopResult = main(Query)
  File "/Users/Linting/Google Drive/CSC510/Project/SE-16/git_helper/GoogleSearch/googleserach.py", line 57, in main
    [QuestionDic, AnswerList] = scrape_webs()
  File "/Users/Linting/Google Drive/CSC510/Project/SE-16/git_helper/GoogleSearch/googleserach.py", line 42, in scrape_webs
    QuestionDic = QuesParser.make_question()
  File "/Users/Linting/Google Drive/CSC510/Project/SE-16/git_helper/stack_overflow_parser/QuestionParser.py", line 23, in make_question
    question_text = self.get_question_text(input_str)
  File "/Users/Linting/Google Drive/CSC510/Project/SE-16/git_helper/stack_overflow_parser/QuestionParser.py", line 35, in get_question_text
    question_tr = question_soup.findAll("div", {'class': "post-text"})[0]
IndexError: list index out of range

**Comment by lintingxue** [comment]
Google search stactover , it returns link of over all result, http://stackoverflow.com/questions/linked/161813?pagesize=30&sort=unanswered
which is not what we what.

**Comment by lintingxue** [comment]
Problem solved.

**Comment by lintingxue** [comment]
Problem solved.
